// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApiTask1.Models
{
    public partial class Phone
    {
        public long Id { get; set; }
        public string Type { get; set; }
        [StringLength(10)]
        public string Number { get; set; }
        [StringLength(36)]
        public string PersonId { get; set; }

        [ForeignKey("PersonId")]
        [InverseProperty("Phone")]
        public virtual Person Person { get; set; }
    }
}